-- BLTK_ANTICHEAT V5

ServerConfig = {}
-- [[READ THIS!]]
-- [[Always configure your anticheat properly, a bad configuration can cause false positives, and ban innocent players. Turn off what you don't need, turn on what you need, and fill the tables properly.]]

-- BYPASS ACE: bltk-ac.bypass
-- ADMIN ACE: bltk-ac.admin

ServerConfig.DebugMode = false -- Debug Mode, prevent players from getting banned and kicked, only use it for troubleshooting and other testing stuff. This function will also disable bypass, to let admins to troubleshoot the Anticheat.
ServerConfig.KickMessage = "Reason: " -- Change this
ServerConfig.BanMessage = "⚔️ BLTK Anticheat ⚔️ | You have been banned from this Server for cheating, this ban will never expire." -- Change this

ServerConfig.UsernameBlacklist = true
ServerConfig.UsernameBlacklistKickReason = "Your name is blacklisted on this server"
ServerConfig.BlacklistedUsernames = {
	"administrator",
	"admin",
	"adm1n",
	"adm!n",
	"admln",
	"moderator",
	"owner",
	"nigger",
	"anyád",
	"buzi",
	"eulencheats",
	"lynxmenu",
	"geci",
	"hacker",
	"bastard",
	"hamhaxia",
	"333gang",
	"ukrp",
	"eguk",
	"n1gger",
	"n1ga",
	"nigga",
	"n1gga",
	"nigg3r",
	"nig3r",
	"shagged",
	"4dm1n",
	"<",
	">",
	"~",
	"4dmin",
	"m0d3r4t0r",
	"n199er",
	"n1993r",
	"rustchance.com",
	"rustchance",
	"hellcase.com",
	"hellcase",
	"youtube.com",
	"youtu.be",
	"youtube",
	"twitch.tv",
	"twitch",
	"anticheat.gg",
	"anticheat",
	"fucking",
	"chocohax",
	"civilgamers.com",
	"civilgamers",
	"csgoempire.com",
	"csgoempire",
	"g4skins.com",
	"g4skins",
	"gameodds.gg",
	"duckfuck.com",
	"crysishosting.com",
	"crysishosting",
	"skinhub.com",
	"skinhub",
	"casedrop.eu",
	"casedrop",
	"cs.money",
	"rustypot.com",
	"rampage.lt",
	"?",
	"xcasecsgo.com",
	"xcasecsgo",
	"csgocases.com",
	"csgocases",
	"K9GrillzUK.co.uk",
	"moat.gg",
	"princevidz.com",
	"princevidz",
	"pvpro.com",
	"kurva",
	"ez.krimes.ro",
	"loot.farm",
	"arma3fisherslife.net",
	"arma3fisherslife",
	"egamers.io",
	"ifn.gg",
	"sups.gg",
	"tradeit.gg",
	"§",
	"csgotraders.net",
	"csgotraders",
	"hurtfun.com",
	"hurtfun",
	"gamekit.com",
	"t.tv",
	"yandex.ru",
	"yandex",
	"csgofly.com",
	"csgofly",
	"pornhub.com",
	"pornhub",
	"cs.deals",
	"twat",
	"STRESS.PW",
}

ServerConfig.AntiESX = false -- ONLY ENABLE THIS IF YOU ARE NOT USING ESX!
ServerConfig.AntiESXKick = false
ServerConfig.AntiESXBan = false

ServerConfig.ClearPedTasksImmediately = true -- Detects if someone is trying to ClearPedTasksImmediately other players (most likely trying to kick players from vehicles)
ServerConfig.ClearPedTasksImmediatelyKick = false
ServerConfig.ClearPedTasksImmediatelyBan = false

ServerConfig.WeaponCheckSwitch = false -- Masterswitch of the weapon check system.
ServerConfig.WeaponKick = true -- Kick players, if the weapon protection system catch cheaters.
ServerConfig.WeaponBan = true -- Ban players, if the weapon protection system catch cheaters.
ServerConfig.WeaponRemoveCheck = false -- This function can be useful, but it will not work correctly on a few servers.
ServerConfig.WeaponAddCheck = false -- This function can be useful, but it will not work correctly on a few servers.

ServerConfig.AntiEntityNuke = true
ServerConfig.MaxPeds = 110 -- Max ped spawn/5 sec
ServerConfig.MaxVehs = 12 -- Max vehicle spawn/5 sec
ServerConfig.AntiEntityNukeKick = true
ServerConfig.AntiEntityNukeBan = true

ServerConfig.ParticleFX = true -- A really useful particleFX detector system.
ServerConfig.ParticleFXSpamDetecter = true -- Anti ParticleFX Spammer system.
ServerConfig.ParticleFXSpamDetecterMaxFX = 7 -- Particle FX limit / 5 sec. A good starting point is 7
ServerConfig.ParticleFXSpamKick = true
ServerConfig.ParticleFXSpamBan = true

ServerConfig.AntiExplosionNuke = true -- Anti explosion nuke system, this will detect a lot of cheats, if you configure it properly.
ServerConfig.AntiExplosionSpam = true
ServerConfig.AntiExplosionSpamKick = true
ServerConfig.AntiExplosionSpamBan = false
ServerConfig.MaxExplosionPerFiveSec = 20 -- How much explosion is creatable in 5 sec.

ServerConfig.ExplosionDetections = {
	[0] = { name = "Grenade", log = false, kick = false, ban = false },
	[1] = { name = "GrenadeLauncher", log = true, kick = false, ban = false },
	[3] = { name = "Molotov", log = true, kick = true, ban = true },
	[4] = { name = "Rocket", log = true, kick = false, ban = false },
	[5] = { name = "TankShell", log = false, kick = false, ban = false },
	[6] = { name = "Hi_Octane", log = false, kick = false, ban = false },
	[7] = { name = "Car", log = false, kick = false, ban = false },
	[8] = { name = "Plance", log = true, kick = false, ban = false },
	[9] = { name = "PetrolPump", log = false, kick = false, ban = false },
	[10] = { name = "Bike", log = false, kick = false, ban = false },
	[11] = { name = "Dir_Steam", log = false, kick = false, ban = false },
	[12] = { name = "Dir_Flame", log = false, kick = false, ban = false },
	[13] = { name = "Dir_Water_Hydrant", log = false, kick = false, ban = false },
	[14] = { name = "Dir_Gas_Canister", log = false, kick = false, ban = false },
	[15] = { name = "Boat", log = false, kick = false, ban = false },
	[16] = { name = "Ship_Destroy", log = false, kick = false, ban = false },
	[17] = { name = "Truck", log = false, kick = false, ban = false },
	[18] = { name = "Bullet", log = false, kick = false, ban = false },
	[19] = { name = "SmokeGrenadeLauncher", log = false, kick = false, ban = false },
	[20] = { name = "SmokeGrenade", log = false, kick = false, ban = false },
	[21] = { name = "BZGAS", log = false, kick = false, ban = false },
	[22] = { name = "Flare", log = false, kick = false, ban = false },
	[23] = { name = "Gas_Canister", log = false, kick = false, ban = false },
	[24] = { name = "Extinguisher", log = false, kick = false, ban = false },
	[25] = { name = "Programmablear", log = false, kick = false, ban = false },
	[26] = { name = "Train", log = true, kick = false, ban = false },
	[27] = { name = "Barrel", log = false, kick = false, ban = false },
	[28] = { name = "PROPANE", log = false, kick = false, ban = false },
	[29] = { name = "Blimp", log = true, kick = true, ban = true },
	[30] = { name = "Dir_Flame_Explode", log = false, kick = false, ban = false },
	[31] = { name = "Tanker", log = false, kick = false, ban = false },
	[32] = { name = "PlaneRocket", log = true, kick = false, ban = false },
	[33] = { name = "VehicleBullet", log = true, kick = true, ban = true },
	[34] = { name = "Gas_Tank", log = false, kick = false, ban = false },
	[35] = { name = "FireWork", log = false, kick = false, ban = false },
	[36] = { name = "SnowBall", log = false, kick = false, ban = false },
	[37] = { name = "ProxMine", log = false, kick = false, ban = false },
	[38] = { name = "Valkyrie_Cannon", log = true, kick = true, ban = true },
}

ServerConfig.ChatController = true -- Chat control system
ServerConfig.ChatAntiSpam = true -- Anti chat spam
ServerConfig.MaxMessageSpam = 10 -- Max messages / 5 sec
ServerConfig.ChatAntiSpamKick = true
ServerConfig.ChatAntiSpamBan = false
ServerConfig.ChatBlacklistedWord = true -- Word blacklist system, this can be useful.
ServerConfig.BlacklistedWords = {
    "killmenu",
    "panik",
    "ssssss",
    "brutan",
    "brutanpremium",
    "hammafia",
	"purgemenu",
    "hamhaxia",
    "redstonia",
    "hoax",
    "desudo",
    "jd",
    "ham",
    "lua options",
    "God Mode",
    "Maestro",
    "FunCtionOk",
    "lynx9_fixed",
    "Fucked",
	"injected",
	"vRP",
	"deleted due to u being a nigger",
	"Dopamine injected successfully",
    "parent menu doesn",
    "www.d0pamine.xyz",
    "d0pamine v1.1 by Nertigel",
	"d0pamine",
	"lynx",
	"FOriv gay",
	"TiagoModz#1478",
	"WarMenu",
	"tiago",
	"TiagoModz",
	"dopamina",
	"Nertigel: This server is protected and the menu is not gonna work here.",
	"Information",
	"dopamine",
	"KP",
	"opk",
	"jolmany",
        "SovietH4X",
	"Desudo",
	"Brutan",
	"EulenCheats",
	"Lynx 8",
	"www.lynxmenu.com",
	"HamHaxia",
	"Ham Mafia",
	"www.renalua.com",
	"anyad",
	"genyó",
	"geci",
	"szar",
	"kurva",
	"köcsög",
	"kocsog",
	"anyád",
	"lynxmenu.com",
	"Anti-Lynx",
	"Baran#8992",
	"iLostName#7138",
	"Melon#1379",
	"hammafia.com",
	"AlphaV ~ 5391",
	"vjuton.pl",
	"Soviet Bear",
	"MARVIN menu",
	"Alpha Menu",
	"Tiafall",
	"KoGuSzEk#3251",
}
ServerConfig.ChatBlacklistedWordKick = true
ServerConfig.ChatBlacklistedWordBan = true
ServerConfig.BlacklistedEventsSystem = true -- This is a really good tool against newbie cheaters. If you configure this function properly, you can find a lot of cheaters.
ServerConfig.BlacklistedEventKick = false
ServerConfig.BlacklistedEventBan = false
ServerConfig.BlacklistedEvents = {
	"redst0nia:checking",
	"hentailover:xdlol",
	"antilynx8:anticheat",
	"antilynxr6:detection",
	"antilynx8r4a:anticheat",
	"antilynxr4:detect",
	"ynx8:anticheat",
	"lynx8:anticheat",
	"adminmenu:allowall",
	"h:xd",
	"FAC:EzExec",
	"8321hiue89js",
	"adminmenu:allowall",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"AdminMenu:giveDirtyMoney",
	"Tem2LPs5Para5dCyjuHm87y2catFkMpV",
	"dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
	"antilynx8:anticheat",
	"antilynxr4:detect",
	"antilynxr6:detection",
	"ynx8:anticheat",
	"antilynx8r4a:anticheat",
	"lynx8:anticheat",
	"AntiLynxR4:kick",
	"AntiLynxR4:log",
	"bank:deposit",
	"bank:withdraw",
	"Banca:deposit",
	"Banca:withdraw",
	"BsCuff:Cuff696999",
	"CheckHandcuff",
	"cuffServer",
	"cuffGranted",
	"DiscordBot:playerDied",
	"DFWM:adminmenuenable",
	"DFWM:askAwake",
	"DFWM:checkup",
	"DFWM:cleanareaentity",
	"DFWM:cleanareapeds",
	"DFWM:cleanareaveh",
	"DFWM:enable",
	"DFWM:invalid",
	"DFWM:log",
	"DFWM:openmenu",
	"DFWM:spectate",
	"DFWM:ViolationDetected",
	"eden_garage:payhealth",
	"ems:revive",
	"esx_banksecurity:pay",
	"esx_blanchisseur:startWhitening",
	"esx_carthief:alertcops",
	"esx:enterpolicecar",
	"esx_fueldelivery:pay",
	"esx:giveInventoryItem",
	"esx_garbagejob:pay",
	"esx_godirtyjob:pay",
	"esx_gopostaljob:pay",
	"esx_handcuffs:cuffing",
	"esx_jail:sendToJail",
	"esx_jail:unjailQuest",
	"esx_jailer:sendToJail",
	"esx_jailer:unjailTime",
	"esx_jobs:caution",
	"esx_mecanojob:onNPCJobCompleted",
	"esx_mechanicjob:startHarvest",
	"esx_mechanicjob:startCraft",
	"esx_pizza:pay",
	"esx_policejob:handcuff",
	"esx_policejob:requestarrest",
	"esx-qalle-jail:jailPlayer",
	"esx-qalle-jail:jailPlayerNew",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:sell",
	"esx_ranger:pay",
	"esx:removeInventoryItem",
	"esx_truckerjob:pay",
	"esx_skin:responseSaveSkin",
	"esx_slotmachine:sv:2",
	"esx_society:getOnlinePlayers",
	"esx_society:setJob",
	"esx_vehicleshop:setVehicleOwned",
	"hentailover:xdlol",
	"JailUpdate",
	"js:jailuser",
	"js:removejailtime",
	"LegacyFuel:PayFuel",
	"ljail:jailplayer",
	"lscustoms:payGarage",
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",
	"mellotrainer:s_adminKill",
	"NB:destituerplayer",
	"NB:recruterplayer",
	"OG_cuffs:cuffCheckNearest",
	"paramedic:revive",
	"police:cuffGranted",
	"unCuffServer",
	"uncuffGranted",
	"vrp_slotmachine:server:2",
	"whoapd:revive",
	"gcPhone:_internalAddMessageDFWM",
	"gcPhone:tchat_channelDFWM",
	"esx_vehicleshop:setVehicleOwnedDFWM",
	"esx_mafiajob:confiscateDFWMPlayerItem",
	"_chat:messageEntDFWMered",
	"lscustoms:pDFWMayGarage",
	"vrp_slotmachDFWMine:server:2",
	"Banca:dDFWMeposit",
	"bank:depDFWMosit",
	"esx_jobs:caDFWMution",
	"give_back",
	"esx_fueldDFWMelivery:pay",
	"esx_carthDFWMief:pay",
	"esx_godiDFWMrtyjob:pay",
	"esx_pizza:pDFWMay",
	"esx_ranger:pDFWMay",
	"esx_garbageDFWMjob:pay",
	"esx_truckDFWMerjob:pay",
	"AdminMeDFWMnu:giveBank",
	"AdminMDFWMenu:giveCash",
	"esx_goDFWMpostaljob:pay",
	"esx_baDFWMnksecurity:pay",
	"esx_sloDFWMtmachine:sv:2",
	"esx:giDFWMveInventoryItem",
	"NB:recDFWMruterplayer",
	"esx_biDFWMlling:sendBill",
	"esx_jDFWMailer:sendToJail",
	"esx_jaDFWMil:sendToJail",
	"js:jaDFWMiluser",
	"esx-qalle-jail:jailPDFWMlayer",
	"LegacyFuel:PayFuDFWMel",
	"OG_cuffs:cuffCheckNeDFWMarest",
	"CheckHandcDFWMuff",
	"cuffSeDFWMrver",
	"cuffGDFWMranted",
	"police:cuffGDFWMranted",
	"esx_handcuffs:cufDFWMfing",
	"esx_policejob:haDFWMndcuff",
	"bank:withdDFWMraw",
	"esx_skin:responseSaDFWMveSkin",
	"esx_mechanicjob:starDFWMtCraft",
	"esx_drugs:startHarvestWDFWMeed",
	"esx_drugs:startTransfoDFWMrmWeed",
	"esx_drugs:startSellWeDFWMed",
	"esx_drugs:startHarvestDFWMCoke",
	"esx_drugs:startTransDFWMformCoke",
	"esx_drugs:startSellCDFWMoke",
	"esx_drugs:startHarDFWMvestMeth",
	"esx_drugs:startTDFWMransformMeth",
	"esx_drugs:startSellMDFWMeth",
	"esx_drugs:startHDFWMarvestOpium",
	"esx_drugs:startSellDFWMOpium",
	"esx_drugs:starDFWMtTransformOpium",
	"esx_blanchisDFWMseur:startWhitening",
	"esx_drugs:stopHarvDFWMestCoke",
	"esx_drugs:stopTranDFWMsformCoke",
	"esx_drugs:stopSellDFWMCoke",
	"esx_drugs:stopHarvesDFWMtMeth",
	"esx_drugs:stopTranDFWMsformMeth",
	"esx_drugs:stopSellMDFWMeth",
	"esx_drugs:stopHarDFWMvestWeed",
	"esx_drugs:stopTDFWMransformWeed",
	"esx_drugs:stopSellWDFWMeed",
	"esx_drugs:stopHarvestDFWMOpium",
	"esx_drugs:stopTransDFWMformOpium",
	"esx_drugs:stopSellOpiuDFWMm",
	"esx_society:openBosDFWMsMenu",
	"esx_jobs:caDFWMution",
	"esx_tankerjob:DFWMpay",
	"esx_vehicletrunk:givDFWMeDirty",
	"gambling:speDFWMnd",
	"AdminMenu:giveDirtyMDFWMoney",
	"esx_moneywash:depoDFWMsit",
	"esx_moneywash:witDFWMhdraw",
	"mission:completDFWMed",
	"truckerJob:succeDFWMss",
	"99kr-burglary:addMDFWMoney",
	"esx_jailer:unjailTiDFWMme",
	"esx_ambulancejob:reDFWMvive",
	"DiscordBot:plaDFWMyerDied",
	"esx:getShDFWMaredObjDFWMect",
	"esx_society:getOnlDFWMinePlayers",
	"js:jaDFWMiluser",
	"h:xd",
	"adminmenu:setsalary",
	"adminmenu:cashoutall",
	"bank:tranDFWMsfer",
	"paycheck:bonDFWMus",
	"paycheck:salDFWMary",
	"HCheat:TempDisableDetDFWMection",
	"esx-qalle-hunting:DFWMreward",
	"esx-qalle-hunting:seDFWMll",
	"esx_mecanojob:onNPCJobCDFWMompleted",
	"BsCuff:Cuff696DFWM999",
	"veh_SR:CheckMonDFWMeyForVeh",
	"esx_carthief:alertcoDFWMps",
	"mellotrainer:adminTeDFWMmpBan",
	"mellotrainer:adminKickDFWM",
	"\78\66\58\100\101\115\116\105\116\117\101\114\112\108\97\121\101\114",
	"blarglebus:finishRoute",
	"\101\115\120\95\106\111\98\115\58\99\97\117\116\105\111\110",
	"\101\100\101\110\95\103\97\114\97\103\101\58\112\97\121\104\101\97\108\116\104",
	"\101\115\120\95\102\117\101\108\100\101\108\105\118\101\114\121\58\112\97\121",
	"'\101\115\120\95\99\97\114\116\104\105\101\102\58\112\97\121",
	"\101\115\120\95\100\109\118\115\99\104\111\111\108\58\112\97\121",
	"\76\101\103\97\99\121\70\117\101\108\58\80\97\121\70\117\101\108",
	"\101\115\120\95\103\111\100\105\114\116\121\106\111\98\58\112\97\121",
	"\101\115\120\95\112\105\122\122\97\58\112\97\121",
	"\101\115\120\95\114\97\110\103\101\114\58\112\97\121",
	"\101\115\120\95\103\97\114\98\97\103\101\106\111\98\58\112\97\121",
	"\101\115\120\95\99\97\114\116\104\105\101\102\58\112\97\121",
	"\101\115\120\95\116\114\117\99\107\101\114\106\111\98\58\112\97\121",
	"\65\100\109\105\110\77\101\110\117\58\103\105\118\101\66\97\110\107",
	"\65\100\109\105\110\77\101\110\117\58\103\105\118\101\67\97\115\104",
	"\101\115\120\95\103\111\112\111\115\116\97\108\106\111\98\58\112\97\121",
	"\101\115\120\95\98\97\110\107\115\101\99\117\114\105\116\121\58\112\97\121",
	"\101\115\120\95\115\108\111\116\109\97\99\104\105\110\101\58\115\118\58\50",
	"\101\115\120\95\112\111\108\105\99\101\106\111\98\58\104\97\110\100\99\117\102\102",
	"\101\115\120\95\100\109\118\115\99\104\111\111\108\58\97\100\100\76\105\99\101\110\115\101",
	"\108\115\99\117\115\116\111\109\115\58\112\97\121\71\97\114\97\103\101",
	"\118\114\112\95\115\108\111\116\109\97\99\104\105\110\101\58\115\101\114\118\101\114\58\50",
	"\76\101\103\97\99\121\70\117\101\108\58\80\97\121\70\117\101\108",
	"\100\109\118\58\115\117\99\99\101\115\115",
	"\66\97\110\99\97\58\100\101\112\111\115\105\116",
	"\98\97\110\107\58\100\101\112\111\115\105\116",
	"\98\97\110\107\58\119\105\116\104\100\114\97\119",
	"\66\97\110\99\97\58\119\105\116\104\100\114\97\119",
	"\101\115\120\45\113\97\108\108\101\45\106\97\105\108\58\106\97\105\108\80\108\97\121\101\114",
	"\101\115\120\95\106\97\105\108\101\114\58\115\101\110\100\84\111\74\97\105\108",
	"\101\115\120\95\106\97\105\108\58\115\101\110\100\84\111\74\97\105\108",
	"\106\115\58\106\97\105\108\117\115\101\114",
	"\101\115\120\45\113\97\108\108\101\45\106\97\105\108\58\106\97\105\108\80\108\97\121\101\114",
	"\101\115\120\95\106\97\105\108\101\114\58\115\101\110\100\84\111\74\97\105\108",
	"\101\115\120\95\106\97\105\108\58\115\101\110\100\84\111\74\97\105\108",
	"\106\115\58\106\97\105\108\117\115\101\114",
	"\97\100\118\97\110\99\101\100\70\117\101\108\58\115\101\116\69\115\115\101\110\99\101",
	"\101\115\120\95\100\114\117\103\115\58\115\116\97\114\116\72\97\114\118\101\115\116\87\101\101\100",
	"\101\115\120\95\100\114\117\103\115\58\115\116\97\114\116\84\114\97\110\115\102\111\114\109\87\101\101\100",
	"\101\115\120\95\100\114\117\103\115\58\115\116\97\114\116\83\101\108\108\87\101\101\100",
	"\101\115\120\95\98\108\97\110\99\104\105\115\115\101\117\114\58\115\116\97\114\116\87\104\105\116\101\110\105\110\103",
	"esx_jailer:jailhype",
	"hazerp:wyslijdopaki",
	"esx-qalle-jail:Wiezienie",
	"esx_biAhojJsemGayTesiMelling:sendBill",
	"esx-qalle-jail:jailPASJdkjaawI566gfdlayerme",
	"esx_jaAhojJsemGayTesiMeil:sendToJail",
	"esx_windowcleaner:GiveItem",
	"DiscordBot:plaLittleACyerDied",
	"esx_addons_gcphone:startCall",
	"gcPhone:_internalAddMessage",
	"esx_mugging:giveItems",
	"garage:addKeys",
	"esx_givecarkeys:setVehicleOwnedPlayerId",
	"esx_vehicleshop:setVehicleOwnedPlayerId",
	"fejksensekubcajefraje",
	"esx_mafiajob:confiscatePlayerItem",
	"esx_weashopjob:addLicense",
	"esx_airlines:addLicense",
	"gambling:spend",
	"esx_vehicletrunk:giveDirty",
	"265df2d8-421b-4727-b01d-b92fd6503f5e",
	"esx_moneywash:deposit",
	"esx_moneywash:withdraw",
	"mission:completed",
	"truckerJob:success",
	"c65a46c5-5485-4404-bacf-06a106900258",
	"99kr-burglary:addMoney",
	"esx_tankerjob:pay",
	"esx_truckersjob:payy",
	"paycheck:bonus",
	"gtalife:mandat",
	"wyspa_jail:addKartoteka",
	"advancedFuel:setEssence",
	"esx_bikerjob:giveWeapon",
	"esx_communityservice:sendToCommunityService",
	"BsCuff:Cuff696DFWM999",
	"veh_SR:CheckMonDFWMeyForVeh",
	"esx_carthief:alertcoDFWMps",
	"mellotrainer:adminTeDFWMmpBan",
	"mellotrainer:adminKickDFWM",
	"esx_society:putVehicleInGarage",
	"gcPhone:tchat_channel",
	"antilynx8:anticheat",
	"antilynxr6:detection",
	"antilynx8r4a:anticheat",
	"antilynxr4:detect",
	"HCheat:TempDisableDetection",
	"BsCuff:Cuff696999",
	"veh_SR:CheckMoneyForVeh",
	"d0pamine_xyz:getFuckedNigger",
	"crown_xyz:getFuckedNigger",
	"esx:clientLog",
	"kashactersS:DeleteCharacter",
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",
	"esx_society:putVehicleDFWMInGarage"
}

ServerConfig.EventProtection = false
ServerConfig.EventProtectionKick = false
ServerConfig.EventProtectionBan = false
ServerConfig.MaxValuedEvents =
	{ -- This can catch money spamming, on a vulnarable event, and can easily catch other event executions like these. Maxvalue means, if a player triggers a mavalued event, with an argument which is higer then maxvalue, the anticheat will block it.
		["esx_pizza:pay"] = { maxvalue = 1000 },
		["esx_ranger:pay"] = { maxvalue = 1000 },
		["esx_slotmachine:sv:2"] = { maxvalue = 1000 },
		["AdminMenu:giveBank"] = { maxvalue = 1000 },
		["AdminMenu:giveCash"] = { maxvalue = 1000 },
	}
ServerConfig.NegativeVauleEvents =
	{ -- Negative value blocker. Put your jail/communityservice events here, this script will protect your server against cheaters trying to jail everyone etc... DON'T FORGET COMMAS!
		"esx_communityservice:SendToCommunityService",
		"esx-qalle-jail:jailPlayer",
		"esx_billing:sendBill",
		"js:jailuser",
	}
ServerConfig.AntiTriggerSpam = {
	"lester:vendita",
	"fuel:pay",
}
ServerConfig.AntiFakeMessage = true -- Prevents people from sending chat messages with fake names.
ServerConfig.ESXTriggerProtection = false -- Enable this if you have an ESX server. Protects your ESX triggers.


ServerConfig.BlacklistedParticles = { -- You can get particles from here : https://vespura.com/fivem/particle-list/
	[joaat("scr_clown_appears")] = { name = "scr_clown_appears" },
	[joaat("scr_ex1_plane_exp_sp")] = { name = "scr_ex1_plane_exp_sp" },
	[joaat("td_blood_throat")] = { name = "td_blood_throat" },
	[joaat("scr_indep_firework_trailburst")] = { name = "scr_indep_firework_trailburst" },
}

ServerConfig.AntiNuke = true -- Switch of the AntiNuke system
ServerConfig.BlacklistedEntitiesKick = true -- Kick if a player is trying to spawn blacklisted entities (vehicles/peds/objects)
ServerConfig.BlacklistedEntitiesBan = true -- Ban if a player is trying to spawn blacklisted entities (vehicles/peds/objects)
ServerConfig.BlacklistedVehicles = true -- Blacklisted Vehicles
ServerConfig.BlacklistedVehicleList = { -- Just configure this table PROPERLY
	[joaat("blimp2")] = { logname = "Blimp" } ,-- Use joaat native to use vehicle names.
	[joaat("blimp3")] = { logname = "Blimp" },
	[joaat("oppressor")] = { logname = "Oppressor MK1" },
	[joaat("rhino")] = { logname = "Rhino Tank" },
	[joaat("khanjali")] = { logname = "Khanjali Tank" },
	[joaat("oppressor2")] = { logname = "Oppressor MK2" },
	[-150975354] = { logname = "Blimp" }, -- Use hashes to blacklist a vehicle by hash.
}
ServerConfig.BlacklistedPeds = false -- Blacklisted Peds
ServerConfig.BlacklistedPedList = { -- Just configure this table PROPERLY
	[joaat("a_m_y_acult_01")] = { logname = "Acult 01" }, -- Use joaat native to use ped names.
	[joaat("a_m_o_acult_02")] = { logname = "Acult 02" },
	[joaat("a_m_y_acult_02")] = { logname = "Acult 03" },
	[joaat("a_m_o_acult_01")] = { logname = "Acult 04" },
	[joaat("a_m_m_acult_01")] = { logname = "Acult 05" },
	[joaat("s_m_y_swat_01")] = { logname = "Swat" },
	[2109968527] = { logname = "Justin Acult" }, -- Use hashes to blacklist a ped by hash.
}
ServerConfig.BlacklistedObjects = true -- Blacklisted Peds
ServerConfig.BlacklistedObjectList = { -- Just configure this table PROPERLY
	[joaat("stt_prop_stunt_bblock_huge_01")] = { logname = "Stunt Prop" }, -- Use joaat native to use object names.
	[joaat("stt_prop_stunt_bblock_huge_02")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_huge_03")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_huge_04")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_huge_05")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_hump_01")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_hump_02")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_lrg1")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_lrg2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_lrg3")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_mdm1")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_mdm2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_mdm3")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_qp")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_qp2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_qp3")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_sml1")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_sml2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_sml3")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_xl1")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_xl2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bblock_xl3")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bowling_ball")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bowling_pin")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_bowlpin_stand")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_domino")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump15")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump30")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump45")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump_l")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump_lb")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump_loop")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump_m")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump_mb")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_jump_s")] = { logname = "Stunt Prop" },
	[joaat("sr_prop_spec_tube_xxs_04a")] = { logname = "sr_prop_spec_tube_xxs_04a" },
	[joaat("stt_prop_stunt_jump_sb")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_landing_zone_01")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_ramp")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_soccer_ball")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_soccer_goal")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_soccer_lball")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_soccer_sball")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_target")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_target_small")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_bumps")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_cutout")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwlink")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwlink_02")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwsh15")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwshort")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwslope15")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwslope30")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwslope45")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwturn")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_dwuturn")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_exshort")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_fork")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_funlng")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_funnel")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_hill")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_hill2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_jump")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_link")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_otake")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_sh15")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_sh30")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_sh45")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_sh45_a")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_short")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_slope15")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_slope30")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_slope45")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_start")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_start_02")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_straight")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_straightice")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_st_01")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_st_02")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_turn")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_turnice")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_track_uturn")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_crn")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_crn2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_crn_15d")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_crn_30d")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_crn_5d")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_cross")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_end")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_ent")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_fn_01")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_fn_02")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_fn_03")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_fn_04")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_fn_05")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_fork")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_gap_01")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_gap_02")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_gap_03")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_hg")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_jmp")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_jmp2")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_l")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_m")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_qg")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_s")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_speed")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_speeda")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_speedb")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_xs")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_tube_xxs")] = { logname = "Stunt Prop" },
	[joaat("stt_prop_stunt_wideramp")] = { logname = "Stunt Prop" },
	[joaat("p_spinning_anus_s")] = { logname = "p_spinning_anus ufo" },
	[joaat("dt1_05_damage_slod")] = { logname = "dt1_05_damage_slod" },
	[joaat("prop_windmill_01")] = { logname = "prop_windmill_01" },
	[joaat("xs_prop_plastic_bottle_wl")] = { logname = "xs_prop_plastic_bottle_wl" },
	[joaat("prop_vintage_pump")] = { logname = "prop_vintage_pump" },
	[joaat("prop_box_wood06a")] = { logname = "prop_box_wood06a" },
	[joaat("prop_weed_01")] = { logname = "prop_weed_01" },
	[joaat("p_ferris_wheel_amo_l2")] = { logname = "p_ferris_wheel_amo_l2" },
}
